/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06firstfractalali;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author alagh
 */
public class FractalCanvasPanel extends javax.swing.JPanel {

    /**
     * Creates new form FractalCanvasPanel
     */
    public FractalCanvasPanel() {
        // initComponents();
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);    // call the parent version
        Graphics2D g2d = (Graphics2D) g.create();   // canvas for 2d drawing
        int startX = getWidth()/20;
        int endX = getWidth()-getWidth()/20;
        int Y = getHeight()/10;
        int stepY = getHeight()/10;
        g2d.drawLine(startX, Y, endX, Y);
        drawFractal(g2d, startX, endX, Y, stepY);
        
        // g2d.drawLine(getWidth()/20, getHeight()/10, getWidth()-getWidth()/20, getHeight()/10);
        // drawFractal(g2d, getWidth()/20, getWidth()-getWidth()/20, getHeight()/10, getHeight()/10);
        //// g2d.drawLine(0, 0, getWidth(), getHeight());  // top left to bottom right
        //// g2d.drawLine(getWidth(), 0, 0, getHeight());  // top right to bottom left   
    }
    
    private void drawFractal(Graphics2D g2d, int startX, int endX, int Y, int stepY) {
        // 1. condition when the recursion ends
        int width = endX - startX;
        if (width < 3) return;
        // 2. draws the two lines
        Y += stepY; // move the line lower so it does not overlap with the previous one
        g2d.drawLine(startX, Y, startX + width/3, Y); // draw the left line
        g2d.drawLine(endX - width/3, Y, endX, Y); // draw the right line
        // 3. recursive calls, one for each line that we just drew
        drawFractal(g2d, startX, startX + width/3, Y, stepY); // left hand side recursive lines
        drawFractal(g2d, endX - width/3, endX, Y, stepY); // right hand size recursive lines
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
