/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day06trianglefractaleasierali;

import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author alagh
 */
public class TriangleEasierPanel extends javax.swing.JPanel {

    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g.create();
        int x1 = 16, x2 = x1 + 300; // base is 300
        int y1 = 270, y2 = 270;
        int x3 = (x1 + x2)/2;
        int y3 = y1 - (int)(Math.sqrt(3)/2*Math.abs(x2 - x1));
        g2d.drawLine(x1, y1, x2, y2);
        g2d.drawLine(x1, y1, x3, y3);
        g2d.drawLine(x3, y3, x2, y2);
        drawTriangleFractal(g2d, x1, y1, x2, y2, x3, y3);   // call the triangle fractal
    }
    
    private void drawTriangleFractal(Graphics2D g2d, int x1, int y1, int x2, int y2, int x3, int y3) {
        // 1. condition when the recursion ends
        double edgeLen = Math.sqrt((x1-x2)*(x1-x2) + (y1-y2)*(y1-y2));
        if (edgeLen < 6) return;
        
        // 2. draw this iteration
        int xA = (x1+x2)/2;
        int yA = (y1+y2)/2;
        int xB = (x2+x3)/2;
        int yB = (y2+y3)/2;
        int xC = (x1+x3)/2;
        int yC = (y1+y3)/2;
        // g2d.drawPolygon(new int[]{xA, xB, xC}, new int[]{yA, yB, yC}, 3);
        g2d.drawLine(xA, yA, xB, yB);
        g2d.drawLine(xA, yA, xC, yC);
        g2d.drawLine(xC, yC, xB, yB);
        // go on to the next iteration
        drawTriangleFractal(g2d, xA, yA, xB, yB, xC, yC);
    }
    
    /**
     * Creates new form TriangleEasierPanel
     */
    public TriangleEasierPanel() {
        // initComponents();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
